services:
  keycloak:
    image: keycloak/keycloak:latest
    restart: unless-stopped
    ports:
      - 5005:8080
    volumes:
      - ./data/themes:/opt/keycloak/themes
    environment:
      KC_DB: postgres
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    extra_hosts:
      - host.docker.internal:host-gateway # using internal postgresql container that's running on docker
    command:
      - start-dev